image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
  - name: Setup Flask
    command: cd flask && pip install -r requirement.txt && python server.py
    init: true
    openMode: split-right

  - name: Setup Next.js
    command: cd next && npm i && npm run dev
    init: true
