image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
  - name: Setup Flask
    init: cd flask && pip install -r requirement.txt
    command: python server.py
    openMode: split-right

  - name: Setup Next.js
    init: cd next && npm i
    command: npm run dev
